/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as RecetasRouteImport } from './routes/recetas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecetasIdRouteImport } from './routes/recetas.$id'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasRoute = RecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetasIdRoute = RecetasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecetasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/recetas/$id': typeof RecetasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/recetas/$id': typeof RecetasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recetas': typeof RecetasRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/recetas/$id': typeof RecetasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recetas' | '/sobre-mi' | '/recetas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recetas' | '/sobre-mi' | '/recetas/$id'
  id: '__root__' | '/' | '/recetas' | '/sobre-mi' | '/recetas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecetasRoute: typeof RecetasRouteWithChildren
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas': {
      id: '/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof RecetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetas/$id': {
      id: '/recetas/$id'
      path: '/$id'
      fullPath: '/recetas/$id'
      preLoaderRoute: typeof RecetasIdRouteImport
      parentRoute: typeof RecetasRoute
    }
  }
}

interface RecetasRouteChildren {
  RecetasIdRoute: typeof RecetasIdRoute
}

const RecetasRouteChildren: RecetasRouteChildren = {
  RecetasIdRoute: RecetasIdRoute,
}

const RecetasRouteWithChildren =
  RecetasRoute._addFileChildren(RecetasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecetasRoute: RecetasRouteWithChildren,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
